name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      # you can run setup-node here, just make sure it's able to run the Node.js script
      - name: Lint
        run: npx eslint . | tee -a report.txt
        shell: bash
      - name: Convert text to markdown
        run: node ci/create-md-message.js
      - name: Comment on PR
        uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: report.md

